config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :restaurants do
    resources :meals
  end

  resources :orders

  get "/profile/:id", to: "pages#profile", as: :user_profile

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :restaurant
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :meal
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo, :address])

    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo, :address])
  end


end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: [:show, :edit, :update, :destroy]
  before_action :find_restaurant, only: [:new, :create]

  def index
    @meals = Meal.all
  end

  def show;end

  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.restaurant.id = @restaurant
    if @meal.save
      redirect_to user_profile_path(current_user.id)
    else
      render :new
    end
  end

  def edit;end

  def update
    if @meal.update(meal_params)
      redirect_to user_profile_path(current_user.id)
    else
      render :new
    end

  end

  def destroy
  end

  private

  def set_meal
    @meal = Meal.find(params[:id])
  end

  def meal_params
    params.require(:meal).permit(:name, :photo, :price, :description, :restaurant_id)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home, :show ]

  def home
    @restaurants = Restaurant.all
  end

  def profile
    @restaurants = Restaurant.all
    @meals = Meal.all
    @user = current_user.id
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to profile_path(@profile)
    else
      render :new
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:name)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
    @markers = @restaurants.geocoded.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { restaurant: restaurant })
      }
    end


  end

  def show
    @restaurants = Restaurant.all

    @restaurant = Restaurant.find(params[:id])
    @meals = Meal.all

    @markers = @restaurants.geocoded.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { restaurant: restaurant })
      }
    end
  end


  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to user_profile_path
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(
      :name,
      :photo,
      :description,
      :address,
      :latitude,
      :longitude,
      :category,
      :user_id,
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodDelivery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <%= stylesheet_pack_tag 'application' %>
    <!-- google fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">

  </head>

  <body>
    <%= render 'shared/flashes' %>

    <%= yield %>


  </body>
</html>

app/views/meals/_form.html.erb
<%= render 'shared/navbar' %>

<div class="meal-background">
  <div class="container w-75">
    <div class="row">
      <div class="col-lg-6 meal-left-bg mt-5">

      </div>
      <div class="col-lg-6 meal-right-bg mt-5">
        <%= simple_form_for [@restaurant, @meal] do |f| %>
          <%= f.input :name %>
          <%= f.input :photo %>
          <%= f.input :description %>
          <%= f.input :price %>
          <%= f.association :restaurant %>
          <%= f.submit class: "btn btn-post-meal" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/meals/edit.html.erb
<%= render 'form', meal: @meal %>

app/views/meals/new.html.erb
<%= render 'form', meal: @meal %>

app/views/pages/_info_window.html.erb
<h2><%= restaurant.name %></h2>
<p><%= restaurant.address %></p>

app/views/pages/home.html.erb
<div class="banner">
  <%= render 'shared/navbar' %>

  <div class="container">
    <div class="banner-container">
      <h1>Order Delivery & Take-out</h1>
      <p>Find the right meal for today</p>
      <div class="search-bar">
        <input class="input-search" type="text"> <span class="input-btn">Feed me!</span>

      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="restaurant-grid">
    <% @restaurants.each do |restaurant| %>
      <div class="restaurant-card">
        <%= link_to restaurant_path(restaurant.id) do %>
        <img class="img-restaurant" src="<%= restaurant.photo %>" alt="">
        <p><%= restaurant.name %></p>
        <% end %>
      </div>
    <% end %>

  </div>

</div>

app/views/pages/profile.html.erb
<div class="banner">
  <%= render 'shared/navbar' %>
</div>

<div class="container">
  <div class="user-profile-container">
    <img class="user-profile-photo" src="<%= current_user.photo %>" alt="">
    <div class="">
      <h3><%= current_user.first_name %> <%= current_user.last_name %></h3>
      <p><%= current_user.email %></p>
    </div>
    <div class="">
      <%= link_to "Add restaurant profile", new_restaurant_path, class: "btn btn-add-restaurant" %><br>
      <%= link_to "See my orders", new_restaurant_path, class: "btn btn-see-orders mt-3" %>
    </div>
  </div>

  <div class="restaurant-profile-container">
    <% @restaurants.each do |restaurant| %>
      <% if restaurant.id == current_user.id %>
      <div class="profile-restaurant">
        <img class="profile-restaurant-photo" src="<%= restaurant.photo %>" alt="">
        <%= link_to "edit", edit_restaurant_path(restaurant.id), class: "btn btn-edit-restaurant" %>
        <%= link_to "Delete", edit_restaurant_path(restaurant.id), class: "btn btn-delete-restaurant" %>
        <%= link_to "Add Meal", new_restaurant_meal_path(restaurant.id), class: "btn btn-add-meal" %>
      </div>
      <div class="">
        <h2><%= restaurant.name %></h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vel nisi imperdiet, malesuada lacus ac, fermentum dui. Curabitur risus purus, auctor a interdum ut, elementum sit amet ligula. Etiam tincidunt mauris eget leo pulvinar lobortis. Vestibulum tempus lectus in justo congue, eget vestibulum magna dignissim. Aliquam convallis hendrerit purus eu aliquet. Fusce a nibh dignissim, finibus lectus vitae.</p>
      </div>
    </div>
          <div class="meal-profile-container">
            <% @meals.each do |meal| %>
            <% if meal.restaurant_id == restaurant.id %>
              <div class="meal-content mb-3">
                <div class="row">
                  <div class="col-lg-3">
                    <img class="profile-meal-img" src="<%= meal.photo %>" alt="">
                  </div>
                  <div class="col-lg-3">
                    <p><%= meal.name %></p>

                  </div>
                  <div class="col-lg-3">
                    <p><%= meal.price %></p>
                  </div>
                  <div class="col-lg-3">
                    <%= link_to "Edit meal", edit_restaurant_meal_path(restaurant.id), class: "btn btn-info" %>
                  </div>
                </div>
              </div>
            <% end %>
            <% end %>
          </div>

      <% end %>
    <% end %>


</div>

app/views/profiles/_form.html.erb
<%= simple_form_for(profile) do |f| %>
  <%= f.input :name %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/profiles/index.html.erb
<% @profiles.each do |profile| %>
  <p><%= profile.name %></p>
<% end %>

app/views/profiles/new.html.erb
<%= render 'form', profile: @profile %>

app/views/restaurants/_form.html.erb
<%= simple_form_for (restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :latitude %>
  <%= f.input :longitude %>
  <%= f.input :category %>
  <%= f.association :user %>
  <%= f.submit %>
<% end %>

app/views/restaurants/_info_window.html.erb
<h2><%= restaurant.name %></h2>
<p><%= restaurant.address %></p>

app/views/restaurants/edit.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
  <div id="map"
             style="width: 100%; height: 600px;"
             data-markers="<%= @markers.to_json %>"
             data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        </div>

app/views/restaurants/new.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<div class="restaurant-show"
  style="
    background-image:  linear-gradient( rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.6) ), url(<%= @restaurant.photo %>);
    height: 90vh;
    ">
  <%= render 'shared/navbar' %>
  <div class="container">
    <div class="restaurant-header">
      <h1 class="text-center"><%= @restaurant.name %></h1>
      <p><%= @restaurant.description %></p>
    </div>
  </div>
</div>

<div class="container">
  <div class="meal-container">
    <div class="row">
      <div class="col-lg-6">
        <div class="meal-grid">
          <% @meals.each do |meal| %>
            <% if meal.restaurant_id == @restaurant.id %>
              <div class="row">
                <div class="meal-card">
                <div class="col-lg-5 img-meal"
                  style="background-image: url(<%= meal.photo %>);
                  background-size: 100% 100%;
                ">
                </div>
                <div class="col-lg-7">
                  <h3><%= meal.name %></h3>
                  <p><%= meal.description %></p>
                  <p class="meal-price">
                    <%price = meal.price %>
                    <%= link_to "Order Now #{price}", new_order_path(meal.id) %>
                  </p>
                </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="col-lg-6">
        <div id="map"
             style="width: 100%; height: 500px;"
             data-markers="<%= @markers.to_json %>"
             data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="container pt-5">
      <nav class="navbar navbar-custom navbar-expand-lg">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">DELIVERY</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= link_to "Home", root_path, class: "nav-link active" %>
              </li>
              <li class="nav-item">
                <%= link_to "Restaurants", "#", class: "nav-link" %>
              </li>
              <li class="nav-item">
                <% if user_signed_in? %>
                  <%= link_to "Dashboard", user_profile_path(current_user.id), class: "btn btn-custom-login" %>
                <% else %>
                  <%= link_to "Login",  user_session_path, class: "btn btn-custom-login" %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>